In [7]:
import tensorflow as tf
from tensorflow import keras
from keras.utils import np_utils
from keras.utils import load_img, img_to_array
from sklearn.metrics import classification_report

import os

import pandas as pd
import numpy as np
from numpy import asarray
import cv2
from cv2 import cvtColor

import matplotlib.pyplot as plt
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder


In [8]:
label_list = ['!', '"', '#', '$', '%', '&', "’", '(', ')', '*', '+', ',', '-',
       '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':',
       ';', '<', '=', '>', '?', '@', 'A', 'B', 'C', 'D', 'E', 'F', 'G',
       'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T',
       'U', 'V', 'W', 'X', 'Y', 'Z', '[', '\\', ']', '^', '_', '`', 'a',
       'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n',
       'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '{',
       '|', '{', '~']

In [9]:
from PIL import Image
#path = "C:/Users/shubh/Downloads/DD.png"
#path = "C:/Users/shubh/Downloads/BBB.png"
path = "C:/Users/shubh/Downloads/BBB.png"
im = Image.open(path)
im.show()

In [10]:

""" 
img = load_img(path, target_size=(28, 28))

img= img.convert('1')
x = asarray(img)



#x /= 255
x = np.expand_dims(x, axis=0)

#images = np.vstack([x])
 """



" \nimg = load_img(path, target_size=(28, 28))\n\nimg= img.convert('1')\nx = asarray(img)\n\n\n\n#x /= 255\nx = np.expand_dims(x, axis=0)\n\n#images = np.vstack([x])\n "

In [11]:
img = cv2.imread(path)

In [12]:
print(img)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [13]:
img=cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
#cv2.imshow("Pic",img)

img = cv2.bitwise_not(img)
#cv2.imshow("Invert1",img)
#cv2.waitKey(0)

img = cv2.resize(img, (28, 28))
x = asarray(img)

x = np.expand_dims(x, axis=0)

In [14]:
x = np.where(x=='True', 1, x)
x = np.where(x=='False', 0, x)

C:\Users\shubh\AppData\Local\Temp\ipykernel_10840\3158846395.py:1: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  x = np.where(x=='True', 1, x)
C:\Users\shubh\AppData\Local\Temp\ipykernel_10840\3158846395.py:2: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  x = np.where(x=='False', 0, x)


In [15]:
#x= x/255

In [16]:
np.set_printoptions(linewidth = 350)
print(x)

[[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
  [  0   0   0 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255   4   0   0   0   0   0   0   0   0]
  [  0   0   0 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255   1   0   0   0   0   0]
  [  0   0   0 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255   0   0   0   0]
  [  0   0   0   0   0 255 255 255 255 255 255   0   0   0   0   0   0 255 255 255 255 255 255 255   0   0   0   0]
  [  0   0   0   0   0 109 255 255 255 255 255   0   0   0   0   0   0  

In [17]:
print(type(x))
print(x.shape)

<class 'numpy.ndarray'>
(1, 28, 28)


In [18]:
print(type(x))

<class 'numpy.ndarray'>


In [19]:
temp_model_name = tf.keras.models.load_model("C:/Users/shubh/Desktop/Btech/MINI PROJECT/OCR/OCR local file/OCR_MODEL_edited.h5")

In [20]:
ABC = temp_model_name.predict(x)

1/1 [==============================] - 0s 431ms/step


In [21]:
print(ABC)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [22]:
print("highest accuracy " + str(ABC.max()))
max = ABC.max()
print(ABC.sum())

highest accuracy 1.0
1.0


In [23]:
print(ABC.argmax())
index = ABC.argmax()

33


In [24]:
print(len(label_list))

94


In [25]:
print(label_list[index])

B
